spring:
  datasource:
    url: jdbc:h2:file:./data/tutorialDB
    username: sa
    password: password
    driverClassName: org.h2.Driver
    platform: h2
  jpa:
    show-sql: true
    generate-ddl: true

  h2:
    console:
      enabled: true
      path: /h2-console
    hibernate:
      ddl-auto: update
